name: mqttchatterbox
description: A new Flutter project for demonstarting MQTT Protocol Connection.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mqtt_client: ^9.6.2
  provider: ^6.0.1
  # Http Interceptor
  dio: ^4.0.0
  # Connectivity Helper
  connectivity: ^3.0.3
  # Http Logger
  pretty_dio_logger: ^1.1.1
  # Loading Dialog
  flutter_easyloading: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


